const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('controlApi', {
  windowAction: action => ipcRenderer.invoke('control:window', action),
  openGithub: () => ipcRenderer.invoke('control:open-github'),
  serviceStatus: () => ipcRenderer.invoke('control:service-status'),
  startService: id => ipcRenderer.invoke('control:start-service', id),
  stopService: id => ipcRenderer.invoke('control:stop-service', id),
  downloadService: id => ipcRenderer.invoke('control:download-service', id),
  onServiceLog: callback => ipcRenderer.on('control:service-log', (_event, payload) => callback(payload)),
  onServiceState: callback => ipcRenderer.on('control:service-state', () => callback()),
  openExternal: url => ipcRenderer.invoke('control:open-external', url),
  listPlugins: () => ipcRenderer.invoke('control:list-plugins'),
  setPluginEnabled: (relPath, enabled) => ipcRenderer.invoke('control:set-plugin-enabled', relPath, enabled),
  savePluginConfig: (type, name, config) => ipcRenderer.invoke('control:save-plugin-config', type, name, config),
  readPluginReadme: (type, name) => ipcRenderer.invoke('control:read-plugin-readme', type, name),
  installPlugin: (id, repo) => ipcRenderer.invoke('control:install-plugin', id, repo),
  loadConfig: () => ipcRenderer.invoke('control:load-config'),
  getChatHistory: () => ipcRenderer.invoke('control:get-chat-history'),
  environmentInfo: () => ipcRenderer.invoke('control:environment-info'),
  getPrompts: () => ipcRenderer.invoke('control:get-prompts'),
  fetchLlmModels: (apiUrl, apiKey) => ipcRenderer.invoke('control:fetch-llm-models', apiUrl, apiKey),
  listMcpTools: () => ipcRenderer.invoke('control:list-mcp-tools'),
  toggleMcpTool: (type, key) => ipcRenderer.invoke('control:toggle-mcp-tool', type, key),
  getToolMarket: () => ipcRenderer.invoke('control:get-tool-market'),
  downloadTool: tool => ipcRenderer.invoke('control:download-tool', tool),
  saveConfig: config => ipcRenderer.invoke('control:save-config', config),
  listLive2dModels: () => ipcRenderer.invoke('control:list-live2d-models'),
  currentLive2dModel: () => ipcRenderer.invoke('control:current-live2d-model'),
  selectLive2dModel: name => ipcRenderer.invoke('control:select-live2d-model', name),
  loadMotionData: character => ipcRenderer.invoke('control:load-motion-data', character),
  saveMotionData: (character, kind, values) => ipcRenderer.invoke('control:save-motion-data', character, kind, values),
  resetMotionData: (character, kind) => ipcRenderer.invoke('control:reset-motion-data', character, kind),
  triggerMotion: name => ipcRenderer.invoke('control:trigger-motion', name),
  triggerExpression: name => ipcRenderer.invoke('control:trigger-expression', name),
  applyVmc: (host, port) => ipcRenderer.invoke('control:apply-vmc', host, port),
  startLive2d: () => ipcRenderer.invoke('control:start-live2d'),
  stopLive2d: () => ipcRenderer.invoke('control:stop-live2d'),
  onLive2dLog: callback => ipcRenderer.on('control:live2d-log', (_event, text) => callback(text)),
  onToolLog: callback => ipcRenderer.on('control:tool-log', (_event, text) => callback(text)),
  onLive2dState: callback => ipcRenderer.on('control:live2d-state', (_event, running) => callback(running))
});
